import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Wrapper from "./Wrapper/Wrapper";



// Export metadata
export const metadata: Metadata = {
  title: "H-VPN",
  description: "Generated by create next app",
};

// RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <Wrapper>
          {children}
        </Wrapper>
      </body>
    </html>
  );
}
