import type { Metadata } from "next";
import "./globals.css";
import Wrapper from "./Wrapper/Wrapper";

// Metadata export
export const metadata: Metadata = {
  title: "H-VPN",
  description: "Generated by create next app",
};

// RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Main container for the triangle and content */}
        <div className="layout-container">
          {/* Triangle element */}
          <div className="trianglewrapper">
            <div className="triangle"></div>
          </div>

          {/* Wrapper for children */}
          <Wrapper>{children}</Wrapper>
        </div>
      </body>
    </html>
  );
}
